//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoNovitas.LoginSample.Repositories.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.LiteratureItems = new HashSet<LiteratureItem>();
            this.LoanItems = new HashSet<LoanItem>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Author { get; set; }
        public int Publisher { get; set; }
        public int Available { get; set; }
        public string Isbn { get; set; }
        public string Godina { get; set; }
    
        public virtual Author Author1 { get; set; }
        public virtual Publisher Publisher1 { get; set; }
        public virtual ICollection<LiteratureItem> LiteratureItems { get; set; }
        public virtual ICollection<LoanItem> LoanItems { get; set; }
    }
}
