//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoNovitas.LoginSample.Repositories.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literature
    {
        public Literature()
        {
            this.LiteratureItems = new HashSet<LiteratureItem>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<LiteratureItem> LiteratureItems { get; set; }
    }
}
