//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoNovitas.LoginSample.Repositories.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiteratureItem
    {
        public int Book_id { get; set; }
        public int Literature_id { get; set; }
        public int Id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Literature Literature { get; set; }
    }
}
